name: "macOS - Setup Vulkan SDK"
description: "Setup Vulkan SDK for macOS"
inputs:
  path:
    description: "Installation path"
    required: true
  version:
    description: "Vulkan SDK version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Vulkan SDK
      shell: bash
      run: |
        mkdir -p ${{ inputs.path }}
        cd ${{ inputs.path }}
        curl -L -o vulkan_sdk.zip https://sdk.lunarg.com/sdk/download/${{ inputs.version }}/mac/vulkansdk-macos-${{ inputs.version }}.zip
        unzip -q vulkan_sdk.zip
        rm vulkan_sdk.zip
